# version: '3.8'
# services:
#   mysql:
#     image: mysql:8.0
#     container_name: gym-mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: gym_edition_one_db
#       MYSQL_USER: GYM_EDITION_ONE
#       MYSQL_PASSWORD: GYM_EDITION_ONE
#     ports:
#       - "3307:3306"  # Changed host port to 3307, container port remains 3306
#     volumes:
#       - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data: